# Generated by Django 4.2.5 on 2023-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teslim Yeri'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alış Yeri'),
        ),
    ]
