# Generated by Django 4.2.5 on 2023-09-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0002_alter_car_dropoff_location_alter_car_pickup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Kiralanma Tarihi')),
                ('start_time', models.TimeField(verbose_name='Kiralanma Saati')),
                ('return_date', models.DateField(verbose_name='Teslim Tarihi')),
                ('return_time', models.TimeField(verbose_name='Teslim Saati')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.car', verbose_name='Araba')),
            ],
        ),
    ]
