# Generated by Django 4.2.5 on 2023-12-16 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0003_alter_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='orderid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Sipariş ID'),
        ),
    ]
