# Generated by Django 4.2.5 on 2023-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0004_alter_booking_car_alter_booking_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Teslim Yeri'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alış Yeri'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, verbose_name='Teslim Saati'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Alış Tarihi'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, verbose_name='Alış Saati'),
        ),
    ]
