# Generated by Django 4.2.5 on 2023-09-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0005_booking_dropoff_location_booking_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id'], 'verbose_name': 'Rezervasyon', 'verbose_name_plural': 'Rezervasyonlar'},
        ),
    ]
