# Generated by Django 4.2.5 on 2023-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0005_alter_booking_options_alter_booking_orderid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id'], 'verbose_name': 'Rezervasyon', 'verbose_name_plural': 'Rezervasyonlar'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderid',
            field=models.CharField(max_length=9, unique=True, verbose_name='Sipariş ID'),
        ),
    ]
