# Generated by Django 4.2.5 on 2023-10-12 19:14

from django.db import migrations, models
import django.db.models.deletion
import rentacar.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0008_delete_caravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Yakıt Türü')),
            ],
            options={
                'verbose_name': 'Yakıt Türü',
                'verbose_name_plural': 'Yakıt Türleri',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Adı')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modeller',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Seri Adı')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='rentacar.brand')),
            ],
            options={
                'verbose_name': 'Seri',
                'verbose_name_plural': 'Seriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Vites Türü')),
            ],
            options={
                'verbose_name': 'Vites Türü',
                'verbose_name_plural': 'Vites Türleri',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[rentacar.models.validate_year], verbose_name='Yıl'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='model',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='rentacar.series'),
        ),
        migrations.AddField(
            model_name='car',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentacar.series', verbose_name='Seri'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentacar.fueltype', verbose_name='Yakıt Türü'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentacar.transmissiontype', verbose_name='Vites Türü'),
        ),
    ]
