# Generated by Django 4.2.5 on 2023-12-23 11:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0009_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=125, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('blog_image1', models.URLField(blank=True, null=True, verbose_name='Blog Fotoğraf (600x400)')),
                ('blog_recent_image', models.URLField(blank=True, null=True, verbose_name='Sidebar Fotoğraf (400x400)')),
                ('blog_detail_image', models.URLField(blank=True, null=True, verbose_name='Blog Detay Fotoğraf (1200x800)')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['-id'],
            },
        ),
    ]
