# Generated by Django 4.2.5 on 2023-10-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0009_brand_fueltype_model_series_transmissiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='rentacar.brand'),
        ),
    ]
