# Generated by Django 4.2.5 on 2023-10-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0010_model_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Kasa Tipi')),
            ],
            options={
                'verbose_name': 'Kasa Tipi',
                'verbose_name_plural': 'Kasa Tipleri',
            },
        ),
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_seats',
            field=models.CharField(max_length=2, null=True, verbose_name='Koltuk Sayısı'),
        ),
        migrations.AddField(
            model_name='car',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentacar.casetype', verbose_name='Kasa Tipi'),
        ),
    ]
