# Generated by Django 4.2.5 on 2023-10-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0011_casetype_remove_model_brand_car_number_of_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='car',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='car',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='start_time',
        ),
    ]
