# Generated by Django 4.2.5 on 2024-01-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0012_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
