# Generated by Django 4.2.5 on 2023-10-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0012_remove_car_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Plaka Numarası'),
        ),
    ]
