# Generated by Django 4.2.5 on 2024-01-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0013_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('delivered', 'Teslim Edildi'), ('not_delivered', 'Teslim Edilmedi')], default='not_delivered', max_length=15, verbose_name='Durum'),
        ),
    ]
