# Generated by Django 4.2.5 on 2023-10-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0014_alter_casetype_options_alter_fueltype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='number_of_person',
        ),
    ]
