# Generated by Django 4.2.5 on 2024-01-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0014_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('delivered', 'Teslim Edildi'), ('in_renting', 'Kiralamada')], default='not_delivered', max_length=15, verbose_name='Durum'),
        ),
    ]
