# Generated by Django 4.2.5 on 2023-10-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0016_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentacar.vehicletype', verbose_name='Araç Tipi'),
        ),
    ]
