# Generated by Django 4.2.5 on 2023-10-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0017_car_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Günlük Fiyat'),
        ),
    ]
