# Generated by Django 4.2.5 on 2023-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0018_car_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Günlük Fiyat'),
        ),
    ]
