# Generated by Django 4.2.5 on 2023-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0020_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='luggage_volume',
            field=models.IntegerField(max_length=50, verbose_name='Bagaj Hacmi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_doors',
            field=models.IntegerField(max_length=2, verbose_name='Kapı Sayısı'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_seats',
            field=models.IntegerField(max_length=2, null=True, verbose_name='Koltuk Sayısı'),
        ),
    ]
