# Generated by Django 4.2.5 on 2023-10-17 19:11

import django.core.validators
from django.db import migrations, models
import rentacar.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0021_alter_car_luggage_volume_alter_car_number_of_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.PositiveIntegerField(verbose_name='Kilometre'),
        ),
        migrations.AlterField(
            model_name='car',
            name='luggage_volume',
            field=models.PositiveIntegerField(verbose_name='Bagaj Hacmi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_doors',
            field=models.PositiveSmallIntegerField(verbose_name='Kapı Sayısı'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_seats',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Koltuk Sayısı'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Günlük Fiyat'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[rentacar.models.validate_year], verbose_name='Yıl'),
        ),
    ]
