# Generated by Django 4.2.5 on 2023-10-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0024_alter_car_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Kilometre'),
        ),
    ]
