# Generated by Django 4.2.5 on 2023-10-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0025_alter_car_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.PositiveBigIntegerField(verbose_name='Kilometre'),
        ),
    ]
