# Generated by Django 4.2.5 on 2023-10-17 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0026_alter_car_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
